version: '3.8'
services:
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  hazelcast:
    image: hazelcast/hazelcast:5.3
    ports:
      - "5701:5701"
    environment:
      - JAVA_OPTS=-Dhazelcast.local.publicAddress=localhost
    volumes:
      - hazelcast-data:/data
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  redis-data:
  hazelcast-data:
  mongo-data: